ALTER TABLE listings
  ADD COLUMN IF NOT EXISTS gender    VARCHAR(20),
  ADD COLUMN IF NOT EXISTS size      VARCHAR(20),
  ADD COLUMN IF NOT EXISTS condition VARCHAR(20),
  ADD COLUMN IF NOT EXISTS area      VARCHAR(50);
